### ISSUE TITLE
Deleting or Adding a drop forces all of the iframes and dumps to reload

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#32]
THis drastically slows down the site, and should be fixed!

**Comment by julianpoy** [comment]
Edited for accuracy. This bug is more extensive than originally suspected.
For some reason, every time a dump is created or deleted, the backend is being queried for ALL dumps. This causes a complete refresh in the DOM, causing slow load times and high internet usage. Also drains the battery a ton, due to ~4mb download and upload every time page is refreshed.
