### ISSUE TITLE
Create Uninvented Technology

### ISSUE THREAD

**Issue by julianpoy** [torch2424/link-dump#68]
This is a little bit of a sarcastic issue.

Recently discovered, a similar program already exists. So many startups in the world, so many ideas being created and realized at each moment.
Every idea I have ever had already exists. Never before have I created a brainchild that was not born a different mind. I find myself wondering if there is an idea that doesn't exist. Is there something truly and completely individual?

The answer, I fear, is no. As I look deeper into ideas, I challenge exemplary ideas. Consider the automobile, a revolutionary piece of equipment that has changed the face of human existence. Where would humans be without François Isaac de Rivaz's genius brainchild. Was that idea his own?

The answer here, is also no. François Isaac de Rivaz's idea was, in part, a product of his individual brain, however it was not solely his own. Without the discoveries of Thomas Edison, there would be no electricity. Without electricity, the automobile would have had no ignition for its hydrogen fuel.

If we examine the work of Thomas Edison, we find evidence that some of his ideas were not his own. Instead, another inventor was robbed for credit; Nikola Tesla.

Is any idea a unique invention? Perhaps, but most ideas are simply improvements on the past. A brain picks up on a historical creation, and crafts it into something new. This new invention, is an improvement or a more integrated utilization.

With these new principles, how do we exact this towards software? Can we create a revolutionary product, that changes the world? The answer is yes, it is possible. We can create something, however we must also acknowledge that others will come to similar ideas, and that these ideas are not truly and completely original.

The question now, is how do we make link dump revolutionary? How do we create something better? How do we take the ideas of others, and create something magnificent from them?

**Comment by torch2424** [comment]
I think the question we need to ask is, does technology have to be revolutionary. I had this same debate about all the android apps I've made. I mean I made a system monitor, music player, and a calculator as example. none of them are unique technologies, and there's nothing wrong with that.

I think the reason we as tech companies and developers feel this way. As that is what technology does, it revolutionizes the world. But One thing I'd like to say, that's only what we hear about in the news and things. We never hear oh hey, microsoft made cortana, so revolutionary! But I heard about siri every where when it first came out right?

Another thing is, technology is so new. Computers were barely runnin kilobytes of memory in the 80s. a little more 30 years later it can hold thousands times that. What I'm getting at here, we feel technology is so revolutionary is because it grows so fast, so almost everything feels like a revolution. But once something grows it begins to improve itself.

Let's take music for example. Something that's been around forever, and much more than just 30 years old. You think Lil Wayne's new song is gonna be revolutionary? No, it's just gonna be another hip hop track. I'll even say J dilla isnt revolutionary. What he did, djs had been doing for years before him. But just because he isnt revolutionary in music and created some brand new never seen hip hop or genre, doesnt mean he's a legend, and an amazing artist.

Just because something like linkDrops exists, doesnt mean it can't be a great and respected piece of software. Just because your not original, doesn't mean you cant make something great.

**Comment by torch2424** [comment]
HAHAHAHA I just found out raindrop.io isnt a website, its a plugin fror chrome too btw :')

Oh wait I got it, but it was a weird login.

Oh my god this UI is terrible, no feed embedding, has these weird folders, feed is weird, and the site is slow. 

Beautiful design in my opinion though

**Comment by torch2424** [comment]
I feel like this philisophical issue can be closed now :)
